name: Build (CI)

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/build.yml
      - name: Build site
        run: npm run build
